services:
  - type: web
    name: chatgpt-telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    region: oregon
    plan: free
    pythonVersion: 3.11
